[33md1a0b1e[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mmain[m[33m, [m[1;31morigin/main[m[33m)[m seo-max: 166 mesh-linked pages with JSON-LD + live stats, RSS feed, MCP server.json
 docs/ai-agent-escrow-jobs.html             |  23 [32m++++++[m
 docs/burner-wallet-api.html                |  23 [32m++++++[m
 docs/feed.xml                              |   1 [32m+[m
 docs/index.html                            | 109 [32m++++[m[31m-------------------------[m
 docs/prompt-injection-scanner.html         |  23 [32m++++++[m
 docs/scrape-airbnb-ai-agent.html           |  46 [32m++++++[m[31m------[m
 docs/scrape-airbnb-with-claude.html        |  23 [32m++++++[m
 docs/scrape-airbnb-with-python.html        |  23 [32m++++++[m
 docs/scrape-amazon-ai-agent.html           |  46 [32m++++++[m[31m------[m
 docs/scrape-amazon-with-claude.html        |  23 [32m++++++[m
 docs/scrape-amazon-with-python.html        |  23 [32m++++++[m
 docs/scrape-bestbuy-ai-agent.html          |  46 [32m++++++[m[31m------[m
 docs/scrape-bestbuy-with-claude.html       |  23 [32m++++++[m
 docs/scrape-bestbuy-with-python.html       |  23 [32m++++++[m
 docs/scrape-bigcommerce-ai-agent.html      |  46 [32m++++++[m[31m------[m
 docs/scrape-bigcommerce-with-claude.html   |  23 [32m++++++[m
 docs/scrape-bigcommerce-with-python.html   |  23 [32m++++++[m
 docs/scrape-booking-ai-agent.html          |  46 [32m++++++[m[31m------[m
 docs/scrape-booking-with-claude.html       |  23 [32m++++++[m
 docs/scrape-booking-with-python.html       |  23 [32m++++++[m
 docs/scrape-coingecko-ai-agent.html        |  23 [32m++++++[m
 docs/scrape-coingecko-with-claude.html     |  23 [32m++++++[m
 docs/scrape-coingecko-with-python.html     |  23 [32m++++++[m
 docs/scrape-craigslist-ai-agent.html       |  46 [32m++++++[m[31m------[m
 docs/scrape-craigslist-with-claude.html    |  23 [32m++++++[m
 docs/scrape-craigslist-with-python.html    |  23 [32m++++++[m
 docs/scrape-drift-ai-agent.html            |  46 [32m++++++[m[31m------[m
 docs/scrape-drift-with-claude.html         |  23 [32m++++++[m
 docs/scrape-drift-with-python.html         |  23 [32m++++++[m
 docs/scrape-drupal-ai-agent.html           |  46 [32m++++++[m[31m------[m
 docs/scrape-drupal-with-claude.html        |  23 [32m++++++[m
 docs/scrape-drupal-with-python.html        |  23 [32m++++++[m
 docs/scrape-ebay-ai-agent.html             |  46 [32m++++++[m[31m------[m
 docs/scrape-ebay-with-claude.html          |  23 [32m++++++[m
 docs/scrape-ebay-with-python.html          |  23 [32m++++++[m
 docs/scrape-etsy-ai-agent.html             |  46 [32m++++++[m[31m------[m
 docs/scrape-etsy-with-claude.html          |  23 [32m++++++[m
 docs/scrape-etsy-with-python.html          |  23 [32m++++++[m
 docs/scrape-expedia-ai-agent.html          |  46 [32m++++++[m[31m------[m
 docs/scrape-expedia-with-claude.html       |  23 [32m++++++[m
 docs/scrape-expedia-with-python.html       |  23 [32m++++++[m
 docs/scrape-facebook-ai-agent.html         |  46 [32m++++++[m[31m------[m
 docs/scrape-facebook-with-claude.html      |  23 [32m++++++[m
 docs/scrape-facebook-with-python.html      |  23 [32m++++++[m
 docs/scrape-freshdesk-ai-agent.html        |  46 [32m++++++[m[31m------[m
 docs/scrape-freshdesk-with-claude.html     |  23 [32m++++++[m
 docs/scrape-freshdesk-with-python.html     |  23 [32m++++++[m
 docs/scrape-github-ai-agent.html           |  46 [32m++++++[m[31m------[m
 docs/scrape-github-with-claude.html        |  23 [32m++++++[m
 docs/scrape-github-with-python.html        |  23 [32m++++++[m
 docs/scrape-glassdoor-ai-agent.html        |  46 [32m++++++[m[31m------[m
 docs/scrape-glassdoor-with-claude.html     |  23 [32m++++++[m
 docs/scrape-glassdoor-with-python.html     |  23 [32m++++++[m
 docs/scrape-hackernews-ai-agent.html       |  46 [32m++++++[m[31m------[m
 docs/scrape-hackernews-with-claude.html    |  23 [32m++++++[m
 docs/scrape-hackernews-with-python.html    |  23 [32m++++++[m
 docs/scrape-hubspot-ai-agent.html          |  46 [32m++++++[m[31m------[m
 docs/scrape-hubspot-with-claude.html       |  23 [32m++++++[m
 docs/scrape-hubspot-with-python.html       |  23 [32m++++++[m
 docs/scrape-indeed-ai-agent.html           |  46 [32m++++++[m[31m------[m
 docs/scrape-indeed-with-claude.html        |  23 [32m++++++[m
 docs/scrape-indeed-with-python.html        |  23 [32m++++++[m
 docs/scrape-instagram-ai-agent.html        |  46 [32m++++++[m[31m------[m
 docs/scrape-instagram-with-claude.html     |  23 [32m++++++[m
 docs/scrape-instagram-with-python.html     |  23 [32m++++++[m
 docs/scrape-intercom-ai-agent.html         |  46 [32m++++++[m[31m------[m
 docs/scrape-intercom-with-claude.html      |  23 [32m++++++[m
 docs/scrape-intercom-with-python.html      |  23 [32m++++++[m
 docs/scrape-joomla-ai-agent.html           |  46 [32m++++++[m[31m------[m
 docs/scrape-joomla-with-claude.html        |  23 [32m++++++[m
 docs/scrape-joomla-with-python.html        |  23 [32m++++++[m
 docs/scrape-linkedin-ai-agent.html         |  46 [32m++++++[m[31m------[m
 docs/scrape-linkedin-with-claude.html      |  23 [32m++++++[m
 docs/scrape-linkedin-with-python.html      |  23 [32m++++++[m
 docs/scrape-magento-ai-agent.html          |  46 [32m++++++[m[31m------[m
 docs/scrape-magento-with-claude.html       |  23 [32m++++++[m
 docs/scrape-magento-with-python.html       |  23 [32m++++++[m
 docs/scrape-mailchimp-ai-agent.html        |  46 [32m++++++[m[31m------[m
 docs/scrape-mailchimp-with-claude.html     |  23 [32m++++++[m
 docs/scrape-mailchimp-with-python.html     |  23 [32m++++++[m
 docs/scrape-medium-ai-agent.html           |  46 [32m++++++[m[31m------[m
 docs/scrape-medium-with-claude.html        |  23 [32m++++++[m
 docs/scrape-medium-with-python.html        |  23 [32m++++++[m
 docs/scrape-monster-ai-agent.html          |  46 [32m++++++[m[31m------[m
 docs/scrape-monster-with-claude.html       |  23 [32m++++++[m
 docs/scrape-monster-with-python.html       |  23 [32m++++++[m
 docs/scrape-nike-ai-agent.html             |  46 [32m++++++[m[31m------[m
 docs/scrape-nike-with-claude.html          |  23 [32m++++++[m
 docs/scrape-nike-with-python.html          |  23 [32m++++++[m
 docs/scrape-opencart-ai-agent.html         |  46 [32m++++++[m[31m------[m
 docs/scrape-opencart-with-claude.html      |  23 [32m++++++[m
 docs/scrape-opencart-with-python.html      |  23 [32m++++++[m
 docs/scrape-opensea-ai-agent.html          |  23 [32m++++++[m
 docs/scrape-opensea-with-claude.html       |  23 [32m++++++[m
 docs/scrape-opensea-with-python.html       |  23 [32m++++++[m
 docs/scrape-paypal-ai-agent.html           |  46 [32m++++++[m[31m------[m
 docs/scrape-paypal-with-claude.html        |  23 [32m++++++[m
 docs/scrape-paypal-with-python.html        |  23 [32m++++++[m
 docs/scrape-prestashop-ai-agent.html       |  46 [32m++++++[m[31m------[m
 docs/scrape-prestashop-with-claude.html    |  23 [32m++++++[m
 docs/scrape-prestashop-with-python.html    |  23 [32m++++++[m
 docs/scrape-realtor-ai-agent.html          |  46 [32m++++++[m[31m------[m
 docs/scrape-realtor-with-claude.html       |  23 [32m++++++[m
 docs/scrape-realtor-with-python.html       |  23 [32m++++++[m
 docs/scrape-reddit-ai-agent.html           |  46 [32m++++++[m[31m------[m
 docs/scrape-reddit-with-claude.html        |  23 [32m++++++[m
 docs/scrape-reddit-with-python.html        |  23 [32m++++++[m
 docs/scrape-salesforce-ai-agent.html       |  46 [32m++++++[m[31m------[m
 docs/scrape-salesforce-with-claude.html    |  23 [32m++++++[m
 docs/scrape-salesforce-with-python.html    |  23 [32m++++++[m
 docs/scrape-sendgrid-ai-agent.html         |  46 [32m++++++[m[31m------[m
 docs/scrape-sendgrid-with-claude.html      |  23 [32m++++++[m
 docs/scrape-sendgrid-with-python.html      |  23 [32m++++++[m
 docs/scrape-shopify-ai-agent.html          |  46 [32m++++++[m[31m------[m
 docs/scrape-shopify-with-claude.html       |  23 [32m++++++[m
 docs/scrape-shopify-with-python.html       |  23 [32m++++++[m
 docs/scrape-square-ai-agent.html           |  46 [32m++++++[m[31m------[m
 docs/scrape-square-with-claude.html        |  23 [32m++++++[m
 docs/scrape-square-with-python.html        |  23 [32m++++++[m
 docs/scrape-squarespace-ai-agent.html      |  46 [32m++++++[m[31m------[m
 docs/scrape-squarespace-with-claude.html   |  23 [32m++++++[m
 docs/scrape-squarespace-with-python.html   |  23 [32m++++++[m
 docs/scrape-stackoverflow-ai-agent.html    |  46 [32m++++++[m[31m------[m
 docs/scrape-stackoverflow-with-claude.html |  23 [32m++++++[m
 docs/scrape-stackoverflow-with-python.html |  23 [32m++++++[m
 docs/scrape-stripe-ai-agent.html           |  46 [32m++++++[m[31m------[m
 docs/scrape-stripe-with-claude.html        |  23 [32m++++++[m
 docs/scrape-stripe-with-python.html        |  23 [32m++++++[m
 docs/scrape-substack-ai-agent.html         |  46 [32m++++++[m[31m------[m
 docs/scrape-substack-with-claude.html      |  23 [32m++++++[m
 docs/scrape-substack-with-python.html      |  23 [32m++++++[m
 docs/scrape-target-ai-agent.html           |  46 [32m++++++[m[31m------[m
 docs/scrape-target-with-claude.html        |  23 [32m++++++[m
 docs/scrape-target-with-python.html        |  23 [32m++++++[m
 docs/scrape-tripadvisor-ai-agent.html      |  46 [32m++++++[m[31m------[m
 docs/scrape-tripadvisor-with-claude.html   |  23 [32m++++++[m
 docs/scrape-tripadvisor-with-python.html   |  23 [32m++++++[m
 docs/scrape-twilio-ai-agent.html           |  46 [32m++++++[m[31m------[m
 docs/scrape-twilio-with-claude.html        |  23 [32m++++++[m
 docs/scrape-twilio-with-python.html        |  23 [32m++++++[m
 docs/scrape-twitter-ai-agent.html          |  46 [32m++++++[m[31m------[m
 docs/scrape-twitter-with-claude.html       |  23 [32m++++++[m
 docs/scrape-twitter-with-python.html       |  23 [32m++++++[m
 docs/scrape-walmart-ai-agent.html          |  46 [32m++++++[m[31m------[m
 docs/scrape-walmart-with-claude.html       |  23 [32m++++++[m
 docs/scrape-walmart-with-python.html       |  23 [32m++++++[m
 docs/scrape-wix-ai-agent.html              |  46 [32m++++++[m[31m------[m
 docs/scrape-wix-with-claude.html           |  23 [32m++++++[m
 docs/scrape-wix-with-python.html           |  23 [32m++++++[m
 docs/scrape-woocommerce-ai-agent.html      |  46 [32m++++++[m[31m------[m
 docs/scrape-woocommerce-with-claude.html   |  23 [32m++++++[m
 docs/scrape-woocommerce-with-python.html   |  23 [32m++++++[m
 docs/scrape-wordpress-ai-agent.html        |  46 [32m++++++[m[31m------[m
 docs/scrape-wordpress-with-claude.html     |  23 [32m++++++[m
 docs/scrape-wordpress-with-python.html     |  23 [32m++++++[m
 docs/scrape-yelp-ai-agent.html             |  46 [32m++++++[m[31m------[m
 docs/scrape-yelp-with-claude.html          |  23 [32m++++++[m
 docs/scrape-yelp-with-python.html          |  23 [32m++++++[m
 docs/scrape-zendesk-ai-agent.html          |  46 [32m++++++[m[31m------[m
 docs/scrape-zendesk-with-claude.html       |  23 [32m++++++[m
 docs/scrape-zendesk-with-python.html       |  23 [32m++++++[m
 docs/scrape-zillow-ai-agent.html           |  46 [32m++++++[m[31m------[m
 docs/scrape-zillow-with-claude.html        |  23 [32m++++++[m
 docs/scrape-zillow-with-python.html        |  23 [32m++++++[m
 docs/summarize-html-api.html               |  23 [32m++++++[m
 server.json                                |   6 [32m++[m
 166 files changed, 3718 insertions(+), 1320 deletions(-)
